name: "Rust Lambda Builder"
description: "Build lambda binary of Cargo project"
author: Aaron Griffin
inputs:
  git_credentials:
    description: "Git credentials - https://git-scm.com/docs/git-credential-store"
    required: false
  directory:
    description: Relative path under $GITHUB_WORKSPACE where Cargo project is located
    required: false
  cargo_config:
    description: Path to additional cargo config file
    required: false
runs:
  using: "docker"
  image: "docker://sevcosec/rust-lambda-action:1.0.3"
  args:
    - ${{ inputs.directory }}
    - ${{ inputs.git_credentials }}
    - ${{ inputs.cargo_config }}
  post-entrypoint: "cleanup.sh"

branding:
  icon: box
  color: orange
